CREATE TABLE `lotteries` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`source_post_id` integer,
	`product_name_raw` text,
	`normalized_product_name` text,
	`card_type` text,
	`store_name_raw` text,
	`normalized_store_name` text,
	`store_branch_raw` text,
	`normalized_store_branch` text,
	`region` text,
	`normalizer_version` text,
	`application_start_at` text,
	`confirmed_open_at` text,
	`application_end_at` text,
	`application_end_date` text,
	`application_end_precision` text,
	`result_announcement_at` text,
	`result_announcement_date` text,
	`result_announcement_precision` text,
	`purchase_start_at` text,
	`purchase_deadline_at` text,
	`application_url` text,
	`official_information_url` text,
	`app_download_url` text,
	`application_method` text,
	`eligibility_conditions` text,
	`pickup_method` text,
	`payment_method` text,
	`price` text,
	`status` text,
	`completeness_score` text,
	`verification_status` text,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE `post_analyses` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`source_post_id` integer NOT NULL,
	`post_type` text,
	`is_lottery_information` integer,
	`card_type` text,
	`confidence_score` text,
	`analysis_status` text,
	`parser_version` text,
	`prompt_version` text,
	`model_id` text,
	`input_content_hash` text,
	`extracted_data` text,
	`analyzed_at` text,
	`error_message` text,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
